### ISSUE TITLE
failed when run the 'composer require mult1mate/cron-manager' command 

### ISSUE THREAD

**Issue by linjunjie** [MUlt1mate/cron-manager#1]
hi , I get a failure when i run the composer , the whole information is below:

---

andy@AndyMacBookPro:/usr/local/github/php/task/cron-manager$ composer require mult1mate/cron-manager
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Using version ^0.1.0 for mult1mate/cron-manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mult1mate/cron-manager dev-master -> satisfiable by mult1mate/cron-manager[dev-master].
    - Can only install one of: mult1mate/cron-manager[v0.1.0, dev-master].
    - Installation request for mult1mate/cron-manager ^0.1.0 -> satisfiable by mult1mate/cron-manager[v0.1.0].

Installation failed, reverting ./composer.json to its original content.
andy@AndyMacBookPro:/usr/local/github/php/task/cron-manager$

---

I'm not good at composer cmd , is it about the composer command ?

thank you !

**Comment by MUlt1mate** [comment]
Hi! Thanks for the feedback. It must be something with your global settings or composer version.
Try to set version for the package  `composer require mult1mate/cron-manager dev-master` or `composer require mult1mate/cron-manager v0.1.0`
If it's doesn't help please send your composer.json if you can.

**Comment by MUlt1mate** [comment]
Does your project already require this package  **mtdowling/cron-expression**?
If it does the problem should be in different versions. If you can change version then set this one 
**"mtdowling/cron-expression": "v1.0.4"**

**Comment by MUlt1mate** [comment]
It seems that 1.0.4 was outdated. I changed it to dev-master. Try to install new version `composer require mult1mate/cron-manager v0.1.1`

**Comment by MUlt1mate** [comment]
Hey, Andy. How's it going? I'm started to worry about you :)
