### ISSUE TITLE
tasks are run one by one,when it a much cron jobs,it will get slow and run at unexpected time

### ISSUE THREAD

**Issue by ihipop** [MUlt1mate/cron-manager#15]
if i have 100 tasks the `Task 99` need to be run at excepted time,but `Task 99`  need to wail `Task 1-98` to finish,and if `Task 98` has a `Fatal Error` which won't be catched. `Task 99` won't be run.
During `Task 99` waiting ,another `Task runner` will be launch...

**Comment by MUlt1mate** [comment]
Sorry, I missed your issue. You can make changes to project and separate tasks by two or more independent schedulers. You can invoke target method from crontab with different parameter and by this parameter define if you need to run task 99 or others. Hope it'll help

**Comment by ihipop** [comment]
Got it.
