### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ActiveRecord\Config' not found 

### ISSUE THREAD

**Issue by bhagyeshsoll** [MUlt1mate/cron-manager#18]
Hello,

I'm using yii2 framework when I execute that time showing me this error.

**Comment by MUlt1mate** [comment]
Hey. what's your command for execution?

**Comment by josematheus10** [comment]
check the variable path
$controller_folder

**Comment by bhagyeshsoll** [comment]
Thanks, @josematheus10 @MUlt1mate. :)
