### ISSUE TITLE
SELECT list is not in GROUP BY clause and contains nonaggregated column

### ISSUE THREAD

**Issue by lxk310** [MUlt1mate/cron-manager#19]
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055
Expression #2 of SELECT list is not in GROUP BY clause and contains
nonaggregated column 't.task_id' which is not functionally
dependent on columns in GROUP BY clause; this is incompatible with
sql_mode=only_full_group_by in

**Comment by filiperhiza** [comment]
It's a problem in a configuration of YOUR MySQL. I'm pretty sure that there is a lot of answers for this problems on Google. It's quite common...

Best Regards

**Comment by lxk310** [comment]
Thank you.
