### ISSUE TITLE
Tasks are not recurring, can you help?

### ISSUE THREAD

**Issue by sukirtipanigrahi** [MUlt1mate/cron-manager#5]
I scheduled a task, however the task is not repeating. Would you mind sharing where all i need to see for the issues.

**Comment by MUlt1mate** [comment]
Hey. Was it executed just once or not at all? 
Here are possible causes:
- you not invoke `TaskRunner::checkAndRunTasks()` properly
- time expression is incorrect  
  Please provide your time expression
