### ISSUE TITLE
Project information

### ISSUE THREAD

**Issue by Pimmetje** [MUlt1mate/cron-manager#6]
Dear developer,

We currently can't get the full project to work. But i have some questions:
Could u give me some more project information?
What is your goal with it, are u planning to continue use/update/support it?

We would like to use something like this module to manage like a 100 php commandline cronjobs. Is this possible?
Would it be possible to add a module to run other php files. Or shell commands?

Can it run tasks for several hours?
Can it start multiple tasks at the same time/minute?
Does it store the output / error output of tasks?
Can i manually fire a cronjob?
Can it stop/kill running cronjobs?

Thanks for your time and effort!

**Comment by MUlt1mate** [comment]
Hello.
Thanks for your attention.
I have plans to add new features, but I'm lack of time now. 
It's not designed to run files or shell commands, but you can wrap it in methods and run them. You can run as many tasks as you want.    

At this time the only way I can imagine to run tasks at the same time is to divide all tasks somehow and add multiple methods that will run them. It's not supported out of the box and I suppose that's not what you want, but I don't have another solution. 

There is not time limit to execution.
It stores output and errors.
You can run them manually.
It can't stop or kill cronjobs.  

I have a demo site, so you can see how would it work like
https://cron.multimate.ru/
